# For more info about Post deployment scripts in Wodby see:
# https://wodby.com/docs/1.0/apps/post-deployment-scripts/
pipeline:
  # This updates the permissions of typically drupal-generatede files which might cause drush cache-rebuild to fail otherwise.
  - name: "Fix permission on cached files."
    type: command
    command: |
      sudo files_chmod /mnt/files/public/css/ || true;
      sudo files_chmod /mnt/files/public/js/ || true ;
      sudo files_chmod /mnt/files/public/languages/ || true ;
      sudo files_chmod /mnt/files/public/php/ || true;
      sudo files_chmod /mnt/files/public/translations/ || true ;
      sudo files_chmod /mnt/files/public/xmlsitemap/ || true;

# Automatically handles drush cr, updb, cim, ...
  - name: Drush Deploy
    type: command
    command: drush deploy
    directory: $WODBY_APP_ROOT
    only_if: '[ -n "$(drush st --fields=bootstrap)" ]'

  - name: Configure administrator and disable password login for '*@ramsalt.com' accounts.
    type: command
    # TODO Remember this: https://www.drupal.org/project/drupal/issues/540008
    command: |
      drush sqlq 'UPDATE users_field_data SET name="Ramsalt Lab", mail="webmaster@ramsalt.com" WHERE uid = 1 LIMIT 1;' ;
      drush sqlq "UPDATE users_field_data SET pass='#' WHERE mail LIKE '%@ramsalt.com';"
    directory: $WODBY_APP_DOCROOT
    only_if: '[ "$WODBY_ENVIRONMENT_TYPE" = "prod" ] && [ -n "$(drush st --fields=bootstrap)" ]'
